<a href="https://colab.research.google.com/github/mobarak91/Edge_IT20002/blob/main/TestNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

test=np.array([1,2,3])
q=15

for i in test:
   print(str(i)+"\n")

1

2

3



In [7]:
test.shape

(3,)

In [8]:
type(test)

numpy.ndarray

In [9]:
test1=np.array([[1,2,3],[4,5,6]])
print(test1)

[[1 2 3]
 [4 5 6]]


3 dimentional array

In [16]:
test3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(test3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
test3.ndim

2

In [18]:
test3.shape

(3, 3)

print value from test3

In [23]:
test3=np.array([[1,2,3],[4,5,6],[7,8,9]])

for row in test3:
    for value in row:
        print(value, end=" ")
    print()

1 2 3 
4 5 6 
7 8 9 
